export enum PermissionActionTypes {
  GET_PERMISSION_LIST_STARTED = 'GET_PERMISSION_LIST_STARTED',
  GET_PERMISSION_LIST_SUCCESS = 'GET_PERMISSION_LIST_SUCCESS',
  GET_PERMISSION_LIST_FAILED = 'GET_PERMISSION_LIST_FAILED',
}
