export enum UserActionTypes {
  GET_USER_STARTED = 'GET_USER_STARTED',
  GET_USER_SUCCESS = 'GET_USER_SUCCESS',
  GET_USER_FAILED = 'GET_USER_FAILED',

  GET_USER_LIST_STARTED = 'GET_USER_LIST_STARTED',
  GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS',
  GET_USER_LIST_FAILED = 'GET_USER_LIST_FAILED',

  CREATE_USER_STARTED = 'CREATE_USER_STARTED',
  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',

  UPDATE_USER_STARTED = 'UPDATE_USER_STARTED',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILED = 'UPDATE_USER_FAILED',

  DELETE_USER_STARTED = 'DELETE_USER_STARTED',
  DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS',
  DELETE_USER_FAILED = 'DELETE_USER_FAILED',

  ASSIGN_USER_PERMISSIONS_STARTED = 'ASSIGN_USER_PERMISSIONS_STARTED',
  ASSIGN_USER_PERMISSIONS_SUCCESS = 'ASSIGN_USER_PERMISSIONS_SUCCESS',
  ASSIGN_USER_PERMISSIONS_FAILED = 'ASSIGN_USER_PERMISSIONS_FAILED',

  GET_USER_PERMISSIONS_STARTED = 'GET_USER_PERMISSIONS_STARTED',
  GET_USER_PERMISSIONS_SUCCESS = 'GET_USER_PERMISSIONS_SUCCESS',
  GET_USER_PERMISSIONS_FAILED = 'GET_USER_PERMISSIONS_FAILED',
}
